## Topics: Hypothesis Testing Exercise

In [16]:
#Q1 
'''Q1. A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. 
A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level.
Please state the assumptions and tests that you carried out to check validity of the assumptions.
     Minitab File : Cutlets.mtw
'''
''' Answer -- 
Assume Null hyposthesis as Ho: μ1 = μ2 
(There is no difference in diameters of cutlets between two units).

Thus Alternate hypothesis as Ha: μ1 ≠ μ2
(There is significant difference in diameters of cutlets between two units) 2 Sample 2 Tail test applicable

Decide a cut-off value
Significance 5%
alpha = 0.05
As it is a two-tailed test
alpha/2 = 0.025
'''

import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

dataset= pd.read_csv(r"D:\Data_Science_course\Data Science @EXCELR\Assignments\3.Hypothesis Testing\Cutlets.csv")
unitA = pd.Series(dataset.iloc[:,0])
unitB = pd.Series(dataset.iloc[:,1])
unitA
unitB



# Two-sample t-test
statistic, p_value = ttest_ind(unitA, unitB)

# Output the results
print("Two-Sample t-test:")
print("Statistic:", statistic)
print("p-value:", p_value)
if p_value < 0.05:
    print("Reject the null hypothesis: There is a significant difference in the mean diameter between Unit A and Unit B.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in the mean diameter between Unit A and Unit B.")



Two-Sample t-test:
Statistic: 0.7228688704678063
p-value: 0.47223947245995
Fail to reject the null hypothesis: There is no significant difference in the mean diameter between Unit A and Unit B.


In [29]:
#Q2
''' 
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) 
of reports of the laboratories on their preferred list. They collected a random sample and recorded 
TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different 
laboratories at 5% significance level.
 
    Minitab File: LabTAT.mtw'''

'''Answer - 
'''

import pandas as pd
from scipy.stats import shapiro

# Step 1: Load Data
# Assuming LabTAT.mtw contains columns named Lab1, Lab2, Lab3, Lab4
data = pd.read_csv(r"D:\Data_Science_course\Data Science @EXCELR\Assignments\3.Hypothesis Testing\LabTAT.csv")

# Rename columns to remove spaces
data.rename(columns=lambda x: x.replace(' ', ''), inplace=True) 
print(data)
import pandas as pd
from scipy.stats import f_oneway, shapiro, levene
# Step 2: Check Assumptions
# Normality Test
normality_tests = {}
for lab in ['Laboratory1', 'Laboratory2', 'Laboratory3', 'Laboratory4']:
    shapiro_test_stat, shapiro_p_value = shapiro(data[lab])
    normality_tests[lab] = {'Shapiro Test Statistic': shapiro_test_stat, 'p-value': shapiro_p_value}

# Homogeneity of Variances Test
levene_test_stat, levene_p_value = levene(data['Laboratory1'], data['Laboratory2'], data['Laboratory3'], data['Laboratory4'])

# Step 3: Perform One-Way ANOVA
f_statistic, anova_p_value = f_oneway(data['Laboratory1'], data['Laboratory2'], data['Laboratory3'], data['Laboratory4'])

# Step 4: Interpret Results
# Print Normality Test Results
print("Normality Test Results:")
for lab, results in normality_tests.items():
    print(f"{lab}: Shapiro Test Statistic = {results['Shapiro Test Statistic']}, p-value = {results['p-value']}")

# Print Homogeneity of Variances Test Result
print(f"\nLevene's Test for Homogeneity of Variances: Test Statistic = {levene_test_stat}, p-value = {levene_p_value}")

# Print One-Way ANOVA Results
print(f"\nOne-Way ANOVA: F-statistic = {f_statistic}, p-value = {anova_p_value}")

# Compare p-value with significance level (0.05)
if anova_p_value < 0.05:
    print("\nThere is a significant difference in the average TAT among the laboratories.")
else:
    print("\nThere is no significant difference in the average TAT among the laboratories.")


     Laboratory1  Laboratory2  Laboratory3  Laboratory4
0         185.35       165.53       176.70       166.13
1         170.49       185.91       198.45       160.79
2         192.77       194.92       201.23       185.18
3         177.33       183.00       199.61       176.42
4         193.41       169.57       204.63       152.60
..           ...          ...          ...          ...
115       178.49       170.66       193.80       172.68
116       176.08       183.98       215.25       177.64
117       202.48       174.54       203.99       170.27
118       182.40       197.18       194.52       150.87
119       182.09       215.17       221.49       162.21

[120 rows x 4 columns]
Normality Test Results:
Laboratory1: Shapiro Test Statistic = 0.990183413028717, p-value = 0.5507769584655762
Laboratory2: Shapiro Test Statistic = 0.9936320185661316, p-value = 0.8637352585792542
Laboratory3: Shapiro Test Statistic = 0.988633930683136, p-value = 0.42045730352401733
Laboratory4: Shapiro

In [48]:
#Q3
''' Sales of products in four different regions is tabulated for males and females. 
Find if male-female buyer rations are similar across regions. '''

''' Answer 
We are going to conduct a Test of Independence using Chi-Square test with Contingency table
We need to check whether the proportion of any of these samples are different or the same?
Null Hypothesis: There is no association or dependency between the gender based buyer rations across regions
Alternative Hypthosis: There is a significant association or dependency between the gender based buyer rations across regions
Deciding a cut-off value

Significance 5%
alpha = 0.05
As it is a one-tailed test

alpha = 1-0.95 = 0.05'''
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.stats import chi2_contingency
buyer = pd.read_csv(r"D:\Data_Science_course\Data Science @EXCELR\Assignments\3.Hypothesis Testing\BuyerRatio.csv")
buyer 
# creating contingency table
observed_values = buyer.iloc[:, 1:].values


# Chi-square test for independence
chi2_stat, p_value, dof, expected_values = chi2_contingency(observed_values)
# Output the results
print("Chi-square Test for Independence:")
print("Chi-square Statistic:", chi2_stat)
print("p-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Values:")
print(expected_values)

if p_value < 0.05:
    print("Reject the null hypothesis: The male-female buyer ratios are not similar across regions.")
else:
    print("Fail to reject the null hypothesis: The male-female buyer ratios are similar across regions.")


Chi-square Test for Independence:
Chi-square Statistic: 1.595945538661058
p-value: 0.6603094907091882
Degrees of Freedom: 3
Expected Values:
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]
Fail to reject the null hypothesis: The male-female buyer ratios are similar across regions.


In [62]:
#Q4
''' TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms.
 Any error in order form renders it defective and has to be reworked before processing.  
 The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences
Minitab File: CustomerOrderForm.mtw
'''
'''Solution --

We are going to conduct a Test of Independence using Chi-Square test with Contingency table
Null Hypothesis: mu1=mu2=mu3=mu4
Alternative Hypthosis: Atleast One of them is Differente
Significance 5%
alpha = 0.05
'''
centers=pd.read_csv(r"D:\Data_Science_course\Data Science @EXCELR\Assignments\3.Hypothesis Testing\Customer_OrderForm.csv")
centers.head(20)
centers.describe()
centers.isnull().sum() # checking for null value
centers[centers.isnull().any(axis=1)]
centers.info() # checking the data type
# print(centers['Phillippines'].value_counts(),'\n',centers['Indonesia'].value_counts(),'\n',centers['Malta'].value_counts(),'\n',centers['India'].value_counts())
contingency_table = [[271,267,269,280],
                    [29,33,31,20]]   # creating contingency table 
print(contingency_table)

# Calculating expected values for observed data
stat, p, df, exp = stats.chi2_contingency(contingency_table)
print("Statistics = ",stat,"\n",'P_Value = ', p,'\n', 'degree of freedom =', df,'\n', 'Expected Values = ', exp)

# Defining Expected values and observed values
observed = np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected = np.array([271.75, 271.75, 271.75, 271.75, 28.25, 28.25, 28.25, 28.25])

# Compare Evidences with Hypothesis using t-statictic

test_statistic , p_value = stats.chisquare(observed, expected, ddof = df)
print("Test Statistic = ",test_statistic,'\n', 'p_value =',p_value)
 
'''
Compare p_value with '
 '(Significane Level)
If p_value is 
 '
 ' we failed to reject Null Hypothesis because of lack of evidence
If p_value is = '
 ' we reject Null Hypothesis
interpreting p-value ''' 

alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis because of lack of evidence ')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB
[[271, 267, 269, 280], [29, 33, 31, 20]]
Statistics =  3.858960685820355 
 P_Value =  0.2771020991233135 
 degree of freedom = 3 
 Expected Values =  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]
Test Statistic =  3.858960685820355 
 p_value = 0.4254298144535761
Significnace=0.050, p=0.425
We fail to reject Null hypothesis because of lack of evidence 
